name: release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    environment: workflows-release
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq -r .version manifest.json'

      - name: build
        run: |
          zip -r "slack-${{ steps.version.outputs.value }}.zip" .
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.pull_request.title }}
          tag_name: ${{ steps.version.outputs.value }}
          generate_release_notes: true
          files: 'slack-${{ steps.version.outputs.value }}.zip'